/* 
*   Muna
*   Copyright © 2025 NatML Inc. All rights reserved.
*/

#nullable enable

namespace Muna.Beta.OpenAI {

    using System;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    /// <summary>
    /// Binary data with an optional content type.
    /// </summary>
    public sealed class BinaryData {

        /// <summary>
        /// Whether this data is empty.
        /// </summary>
        public bool IsEmpty => data.Length == 0;

        /// <summary>
        /// Number of bytes of this data.
        /// </summary>
        public int Length => data.Length;

        /// <summary>
        /// MIME type of this data
        /// </summary>
        public string? MediaType { get; private set; }

        /// <summary>
        /// Convert the `BinaryData` to a byte array.
        /// </summary>
        /// <returns></returns>
        public byte[] ToArray() => data;

        /// <summary>
        /// Gets the value of this instance as bytes without any further interpretation.
        /// </summary>
        public ReadOnlyMemory<byte> ToMemory() => new ReadOnlyMemory<byte>(data);

        private readonly byte[] data;
        
        public BinaryData(byte[] data, string? mediaType = null) {
            this.data = data;
            this.MediaType = mediaType;
        }
    }

    /// <summary>
    /// Embedding.
    /// </summary>
    public sealed class Embedding {

        /// <summary>
        /// The object type, which is always "embedding".
        /// </summary>
        [JsonProperty(@"object")]
#pragma warning disable 8618
        public string Object;
#pragma warning restore 8618

        /// <summary>
        /// Embedding vector as number array.
        /// </summary>
        [JsonProperty(@"embedding")]
        public float[]? Floats;

        /// <summary>
        /// Index of the embedding in the list of embeddings.
        /// </summary>
        [JsonProperty(@"index")]
        public int Index;

        /// <summary>
        /// Embedding vector as a base64 string.
        /// </summary>
        [JsonIgnore]
        public string? Base64;
    }

    public sealed class CreateEmbeddingResponse {

#pragma warning disable 8618
        /// <summary>
        /// The object type, which is always "list".
        /// </summary>
        [JsonProperty(@"object")]
        public string Object;

        /// <summary>
        /// The name of the model used to generate the embedding.
        /// </summary>
        [JsonProperty(@"model")]
        public string Model;

        /// <summary>
        /// The list of embeddings generated by the model.
        /// </summary>
        [JsonProperty(@"data")]
        public Embedding[] Data;
#pragma warning restore 8618

        /// <summary>
        /// The usage information for the request.
        /// </summary>
        [JsonProperty(@"usage")]
        public UsageInfo Usage;

        /// <summary>
        /// Usage information for the request.
        /// </summary>
        public struct UsageInfo {

            /// <summary>
            /// Number of tokens used by the prompt.
            /// </summary>
            [JsonProperty(@"prompt_tokens")]
            public int PromptTokens;

            /// <summary>
            /// Total number of tokens used by the request.
            /// </summary>
            [JsonProperty(@"total_tokens")]
            public int TotalTokens;
        }
    }

    /// <summary>
    /// Chat message.
    /// </summary>
    public sealed class ChatMessage {

        /// <summary>
        /// Message role.
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ChatRole {
            /// <summary>
            /// Assistant.
            /// </summary>
            [EnumMember(Value = @"assistant")]
            Assistant = 1,
            /// <summary>
            /// User
            /// </summary>
            [EnumMember(Value = @"user")]
            User = 2,
            /// <summary>
            /// Developer.
            /// </summary>
            [EnumMember(Value = @"developer")]
            Developer = 3,
            /// <summary>
            /// System.
            /// </summary>
            [EnumMember(Value = @"system")]
            System = 4,
            /// <summary>
            /// Tool.
            /// </summary>
            [EnumMember(Value = @"tool")]
            Tool = 5,
        }

        /// <summary>
        /// Message role.
        /// </summary>
        [JsonProperty(@"role")]
        public ChatRole Role;

        /// <summary>
        /// Message content.
        /// </summary>
        [JsonProperty(@"content")]
        public string? Content;
    }

    /// <summary>
    /// Chat completion.
    /// </summary>
    public sealed class ChatCompletion {

#pragma warning disable 8618
        /// <summary>
        /// The object type, which is always `chat.completion`.
        /// </summary>
        [JsonProperty(@"object")]
        public string Object;

        /// <summary>
        /// Completion unique identifier.
        /// </summary>
        [JsonProperty(@"id")]
        public string Id;

        /// <summary>
        /// Model that generated the chat completion.
        /// </summary>
        [JsonProperty(@"model")]
        public string Model;

        /// <summary>
        /// Chat completion choices.
        /// Can be more than one if `n` is greater than 1.
        /// </summary>
        [JsonProperty(@"choices")]
        public Choice[] Choices;

        /// <summary>
        /// Date created as a unix timestamp (in seconds).
        /// </summary>
        [JsonProperty(@"created")]
        public long Created;

        /// <summary>
        /// Usage statistics for the completion request.
        /// </summary>
        [JsonProperty(@"usage")]
        public UsageInfo Usage;

        public sealed class Choice {

            /// <summary>
            /// Index of this choice in the list of choices.
            /// </summary>
            [JsonProperty(@"index")]
            public int Index;

            /// <summary>
            /// Completion message generated by the model.
            /// </summary>
            [JsonProperty(@"message")]
            public ChatMessage Message;

            /// <summary>
            /// The reason the model stopped generating tokens. This will be:
            /// 
            /// `stop` if the model hit a natural stop point or a provided stop sequence.
            /// `length` if the maximum number of tokens specified in the request was reached.
            /// `content_filter` if content was omitted due to a flag from our content filters.
            /// `tool_calls` if the model called a tool.
            /// `function_call` (deprecated) if the model called a function.
            /// </summary>
            [JsonProperty(@"finish_reason")]
            public string? FinishReason;
        }
#pragma warning restore 8618

        public struct UsageInfo {

            /// <summary>
            /// Number of tokens in the generated completion.
            /// </summary>
            [JsonProperty(@"completion_tokens")]
            public int CompletionTokens;

            /// <summary>
            /// Number of tokens in the prompt.
            /// </summary>
            [JsonProperty(@"prompt_tokens")]
            public int PromptTokens;

            /// <summary>
            /// Total number of tokens used in the request (prompt + completion).
            /// </summary>
            [JsonProperty(@"total_tokens")]
            public int TotalTokens;
        }
    }
    
    /// <summary>
    /// Chat completion chunk.
    /// </summary>
    public sealed class ChatCompletionChunk {

#pragma warning disable 8618
        /// <summary>
        /// The object type, which is always `chat.completion.chunk`.
        /// </summary>
        [JsonProperty(@"object")]
        public string Object;

        /// <summary>
        /// Completion unique identifier.
        /// All chunks from a given completion share the same identifier.
        /// </summary>
        [JsonProperty(@"id")]
        public string Id;

        /// <summary>
        /// Model that generated the chat completion.
        /// </summary>
        [JsonProperty(@"model")]
        public string Model;

        /// <summary>
        /// Chat completion choices.
        /// Can be more than one if `n` is greater than 1.
        /// Can also be empty for the last chunk if you set `stream_options: {"include_usage": true}`.
        /// </summary>
        [JsonProperty(@"choices")]
        public Choice[] Choices;
#pragma warning restore 8618

        /// <summary>
        /// Date created as a unix timestamp (in seconds).
        /// All chunks from a given completion share the same creation timestamp.
        /// </summary>
        [JsonProperty(@"created")]
        public long Created;

        /// <summary>
        /// Usage statistics for the completion request.
        /// </summary>
        [JsonProperty(@"usage")]
        public ChatCompletion.UsageInfo? Usage;

        public sealed class Choice {

            /// <summary>
            /// Index of this choice in the list of choices.
            /// </summary>
            [JsonProperty(@"index")]
            public int Index;

            /// <summary>
            /// Completion message delta generated by the model when streaming.
            /// </summary>
            [JsonProperty(@"delta")]
            public MessageDelta? Delta;

            /// <summary>
            /// The reason the model stopped generating tokens. This will be:
            /// 
            /// `stop` if the model hit a natural stop point or a provided stop sequence.
            /// `length` if the maximum number of tokens specified in the request was reached.
            /// `content_filter` if content was omitted due to a flag from our content filters.
            /// `tool_calls` if the model called a tool.
            /// `function_call` (deprecated) if the model called a function.
            /// </summary>
            [JsonProperty(@"finish_reason")]
            public string? FinishReason;

            public sealed class MessageDelta {

                /// <summary>
                /// Role of the author of this message.
                /// </summary>
                [JsonProperty(@"role")]
                public ChatMessage.ChatRole? Role;

                /// <summary>
                /// Content of the message chunk.
                /// </summary>
                [JsonProperty(@"content")]
                public string? Content;
            }
        }
    }
}