name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        registry-url: "https://registry.npmjs.org"

    - name: Pull Muna C
      run: python3 munac.py --version 0.0.35

    - run: npm publish --access public
      working-directory: Packages/ai.muna.muna